# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flowise-fintricity

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flowisereq.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0956a0009594337aff911d73300ec89 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_89fa318f0c994c3aa1e34a1ef59e6b2a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flowisereq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0956a0009594337aff911d73300ec89 }}/flowisestorage/flowise:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flowise-fintricity'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d3fac14eeadb493dbfb023b2fcd3b83f }}
        images: 'flowisereq.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b0956a0009594337aff911d73300ec89 }}/flowisestorage/flowise:${{ github.sha }}'